// demo/svelte/src/App.svelte
<script lang="ts">
  import KapthaEmailEditor from './lib/KapthaEmailEditor.svelte';

  let design: any = null;

  function handleReady() {
    console.log('Editor ready!');
  }

  function handleDesignChange(event: CustomEvent<any>) {
    console.log('Design changed:', event.detail);
    design = event.detail;
  }

  function handleError(event: CustomEvent<Error>) {
    console.error('Editor initialization failed:', event.detail);
  }

  const customBlocks = [
    {
      id: 'svelte-welcome',
      name: 'Svelte Welcome Block',
      category: 'Marketing',
      components: [
        {
          id: 'svelte-text-1',
          type: 'text',
          props: {
            text: '<h1>Welcome to Svelte + Kaptha</h1>',
            fontSize: '32px',
            fontWeight: 'bold',
            color: '#ff3e00',
            align: 'center'
          }
        },
        {
          id: 'svelte-text-2',
          type: 'text',
          props: {
            text: '<p>Create beautiful emails with Svelte\'s reactive approach.</p>',
            fontSize: '16px',
            color: '#666666',
            align: 'center'
          }
        }
      ]
    }
  ];
</script>

<main>
  <h1>Kaptha Email Editor - Svelte Demo (v3.2.0)</h1>
  <KapthaEmailEditor
    apiKey="kpt_dev_ws001_demo12345678"
    on:ready={handleReady}
    on:designChange={handleDesignChange}
    on:error={handleError}
    {customBlocks}
    minHeight="600px"
  />
  {#if design}
    <div class="design-info">
      <h3>Current Design (Component Count: {design.components?.length || 0})</h3>
    </div>
  {/if}
</main>

// demo/vue/src/App.vue
<template>
  <div>
    <h1>Kaptha Email Editor - Vue 3 Demo (v3.2.0)</h1>
    <KapthaEmailEditorWrapper
      api-key="kpt_dev_ws001_demo12345678"
      :on-ready="handleReady"
      :on-design-change="handleDesignChange"
      :on-error="handleError"
      :custom-blocks="customBlocks"
      min-height="600px"
    />
    <div v-if="design" class="design-info">
      <h3>Current Design (Component Count: {{ design.components?.length || 0 }})</h3>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import KapthaEmailEditorWrapper from './components/KapthaEmailEditorWrapper.vue';

const design = ref<any>(null);

const handleReady = () => {
  console.log('Editor ready!');
};

const handleDesignChange = (newDesign: any) => {
  console.log('Design changed:', newDesign);
  design.value = newDesign;
};

const handleError = (error: Error) => {
  console.error('Editor initialization failed:', error);
};

// Define custom blocks as a constant to prevent recreation
const customBlocks = [
  {
    id: 'vue-welcome',
    name: 'Vue Welcome Block',
    category: 'Marketing',
    components: [
      {
        id: 'vue-text-1',
        type: 'text',
        props: {
          text: '<h1>Welcome to Vue + Kaptha</h1>',
          fontSize: '32px',
          fontWeight: 'bold',
          color: '#42b883',
          align: 'center'
        }
      },
      {
        id: 'vue-text-2',
        type: 'text',
        props: {
          text: '<p>Create beautiful emails with Vue 3 and Composition API.</p>',
          fontSize: '16px',
          color: '#666666',
          align: 'center'
        }
      }
    ]
  }
];
</script>
